use training_db;

-- create view dept_v as select * from depts;
-- SELECT * FROM DEPT_V;

-- INSERT INTO DEPT_V VALUES(180,'PRODUCTION','BANGALORE');
-- SELECT * FROM DEPTS;  -- INSERTED VALUE  THROUGH VIEW IS PRESESNT
-- SELECT * FROM DEPT_V;

-- CREATE VIEW EMP_SAL AS
-- SELECT *,SAL+IFNULL(SAL,0) TOTAL_SAL FROM EMPS;   --SIMILERLY JOINS ALSO CAN DE DONE

-- SELECT * FROM EMP_SAL;


-- CREATE VIEW EMP_JOIN_V AS
-- SELECT E.EMPNO,
--        E.ENAME,
--        E.JOB,
--        E.MGR,
--        E.HIREDATE,
--        E.SAL,
--        E.COMM,
--        E.DEPTNO,
--        M.ENAME AS MANAGER_NAME,
--        D.DNAME,
--        D.LOC,
--        S.GRADE
-- FROM EMPS E
-- JOIN DEPTS D
--     ON D.DEPTNO = E.DEPTNO
-- JOIN SALGRADE S
--     ON E.SAL BETWEEN S.LOSAL AND S.HISAL
-- JOIN EMPS M
--     ON E.MGR = M.EMPNO;

-- SELECT * FROM EMP_JOIN_V ORDER BY GRADE;
-- SELECT * FROM EMP_JOIN_V WHERE GRADE IN(1,3);
-- SELECT GRADE,COUNT(*) FROM EMP_JOIN_V GROUP BY GRADE;

-- CREATE VIEW DEPT_JOB_AGG_V AS
-- SELECT DNAME,
--        JOB,
--        COUNT(*) AS NO_OF_EMP
-- FROM EMPS E
-- JOIN DEPTS D
-- ON E.DEPTNO = D.DEPTNO
-- GROUP BY DNAME, JOB;

-- SELECT * FROM DEPT_JOB_AGG_V;

-- SET autocommit = 1;


-- SQL STAGES TO RUN 
-- stored procedure

-- DELIMITER $$
-- CREATE PROCEDURE GET_ALLEMPS()
-- BEGIN 
-- 	SELECT * FROM EMPS;
-- END $$
-- DELIMITER ;

-- SHOW PROCEDURE STATUS WHERE DB='training_db';

-- CALL GET_ALLEMPS;



-- DELIMITER $$
-- CREATE PROCEDURE GET_ALL_EMPS_(IN DEPT_NO INT)
-- BEGIN 
-- 	SELECT * FROM EMPS
-- 	WHERE DEPTNO=DEPT_NO;
-- END $$
-- DELIMITER ;

-- SHOW PROCEDURE STATUS WHERE DB='training_db';

-- CALL GET_ALL_EMPS_(10);
-- CALL GET_ALL_EMPS_(20);



-- DELIMITER $$

-- CREATE PROCEDURE get_total_salary(
--     IN dept_no INT,
--     OUT total_sal DECIMAL(10,2)
-- )
-- BEGIN
--     SELECT SUM(sal)
--     INTO total_sal
--     FROM emps
--     WHERE deptno = dept_no;
-- END $$

-- DELIMITER ;

-- SET @total  -- [NOT MANDATORY]
-- CALL get_total_salary(30, @total);

-- SELECT @total;

-- DELIMITER $$
-- CREATE PROCEDURE GET_RES(
-- IN NUM1 INT,
-- IN NUM2 INT,
-- OUT RESULT INT )

-- BEGIN 
-- 	SET RESULT:=NUM1+NUM2;
-- END $$;

-- DELIMITER ;

-- CALL GET_RES(10,22,@RESULT);
-- SELECT @RESULT;

-- DELIMITER $$
-- CREATE PROCEDURE CHECK_SLALARY(IN SAL INT)
-- BEGIN
-- 	IF SAL>=5000 THEN 
-- 		SELECT 'hIGH SALARY' AS GRADE;
-- 	ELSEIF SAL BETWEEN 1000 AND 4999 THEN
-- 		SELECT 'MID SALARY'AS GRADE;
-- 	ELSE
-- 		SELECT 'LOW SALARY' AS GRADE;
-- 	END IF;
-- END $$
-- DELIMITER ;


-- CALL  CHECK_SLALARY(10000);
-- CALL  CHECK_SLALARY(1000);
-- CALL  CHECK_SLALARY(500);



-- DROP PROCEDURE PRINT_NUMS;
-- DELIMITER ..
-- CREATE PROCEDURE PRINT_NUMS(IN NUM INT)
-- BEGIN
-- 	DECLARE I INT DEFAULT 1;
--     WHILE I<=NUM DO
-- 		SELECT I;
-- 		SET I=I+1;
-- 	END WHILE;
-- END ..
-- DELIMITER ;

-- CALL PRINT_NUMS(10);




-- DELIMITER ..
-- CREATE PROCEDURE PRINT_NUMS(IN NUM INT)
-- BEGIN
-- 	DECLARE I INT DEFAULT 1;
--     CREATE TEMPORARY TABLE TEMP_TABLE(NUM INT);
--     WHILE I<=NUM DO
-- 		INSERT INTO TEMP_TABLE VALUES (I);
-- 		SET I=I+1;
-- 	END WHILE;
--     
--     SELECT * FROM TEMP_TABLE;
--     DROP TEMPORARY TABLE TEMP_TABLE;
-- END ..
-- DELIMITER ;

-- CALL PRINT_NUMS(10);



-- FUNCTIONS

-- DELIMITER $$
-- CREATE FUNCTION ADD_NUMBERS(A INT,B INT)
-- RETURNS int
-- DETERMINISTIC
-- BEGIN
-- 	RETURN A+B;
-- END $$

-- SELECT ADD_NUMBERS(10,20) AS TOTAL;

-- SELECT EMPNO,ENAME,SAL,ADD_NUMBERS(SAL,1000) AS ADD_1000 FROM EMPS;



-- DELIMITER $$

-- CREATE FUNCTION GET_RANDOM()
-- RETURNS DOUBLE
-- DETERMINISTIC					-- SEE ON NON DETERMINISTIC
-- BEGIN
--     RETURN RAND();
-- END $$

-- DELIMITER ;

-- SELECT GET_RANDOM();


-- TRIGGERS

-- DELIMITER $$
-- CREATE TRIGGER BEFORE_INSERT_EMP
-- BEFORE INSERT ON EMPS
-- FOR EACH ROW 
-- 	BEGIN
-- 		IF NEW.SAL<0 THEN
--         SET NEW.SAL=0;
-- 		END IF;
-- END $$
-- DELIMITER ;

-- INSERT INTO EMPS VALUES(10000,'RAM','MANAGER',100,CURDATE(),-10000,10,10);

-- SELECT * FROM EMPS;


-- CREATE TABLE EMP_LOGS (
--     LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
--     EMPNO INT,
--     ACTION_TYPE VARCHAR(10),
--     LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- DELIMITER $$

-- CREATE TRIGGER EMP_AFTER_INSERT
-- AFTER INSERT ON EMPS
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO EMP_LOGS(EMPNO, ACTION_TYPE)
--     VALUES(NEW.EMPNO, 'INSERT');
-- END $$

-- DELIMITER ;

-- DELIMITER $$

-- CREATE TRIGGER EMP_AFTER_UPDATE
-- AFTER UPDATE ON EMPS
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO EMP_LOGS(EMPNO, ACTION_TYPE)
--     VALUES(NEW.EMPNO, 'UPDATE');
-- END $$

-- DELIMITER ;

-- DELIMITER $$

-- CREATE TRIGGER EMP_AFTER_DELETE
-- AFTER DELETE ON EMPS
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO EMP_LOGS(EMPNO, ACTION_TYPE)
--     VALUES(OLD.EMPNO, 'DELETE');
-- END $$

-- DELIMITER ;


-- INSERT INTO EMPS VALUES (20000,'SHYAM','MANAGER',100,CURDATE(),10000,10,10);

-- UPDATE EMPS
-- SET SAL = 5000
-- WHERE EMPNO = 20000;

-- DELETE FROM EMPS
-- WHERE EMPNO = 20000;


-- SELECT * FROM EMPS;
-- SELECT * FROM EMP_LOGS;


-- DELIMITER $$
-- CREATE TRIGGER before_update_emp
-- BEFORE UPDATE ON EMPS
-- FOR EACH ROW
-- BEGIN
--     IF NEW.sal < OLD.sal THEN
--         SIGNAL SQLSTATE '45000'				-- LOOK ONCE
--         SET MESSAGE_TEXT = 'Salary cannot be decreased';
--     END IF;
-- END $$

-- DELIMITER ;


-- UPDATE EMPS
-- SET SAL = 2000
-- WHERE EMPNO = 20000;


