use training_db;

-- SELECT * FROM  EMPS;
-- SELECT * FROM SALGRADE;

-- DESC EMPS;
-- SELECT E.EMPNO,E.ENAME,E.SAL,S.GRADE FROM EMPS E JOIN SALGRADE S
-- ON E.SAL BETWEEN S.LOSAL AND S.HISAL;


-- SELECT E.EMPNO,E.ENAME,E.SAL,E.DEPTNO,D.DNAME FROM EMPS E,DEPTS D ORDER BY EMPNO;

-- SELECT E.EMPNO,E.ENAME,E.SAL,DEPTNO,D.DNAME,D.LOC FROM EMPS E NATURAL JOIN DEPTS D;

-- SELECT E.EMPNO,E.ENAME,E.SAL,DEPTNO,S.GRADE FROM EMPS E NATURAL JOIN SALGRADE S;   -- IF NO COMMON NAMED CLOUMN,PERFORMS CROSS JOIN

-- SELECT E.EMPNO,E.ENAME,
-- 		E.SAL,E.DEPTNO,
-- 		D.DNAME,S.GRADE
-- 		FROM EMPS E JOIN DEPTS D 
-- 		ON E.DEPTNO=D.DEPTNO
-- 		JOIN SALGRADE S ON
-- 		E.SAL BETWEEN S.LOSAL AND S.HISAL;
        
-- SELECT E.EMPNO,E.ENAME,
-- 		E.SAL,E.DEPTNO,
-- 		D.DNAME,S.GRADE,
--         M.ENAME AS MANAGER_NAME
-- 		FROM EMPS E JOIN DEPTS D 
-- 		ON E.DEPTNO=D.DEPTNO
-- 		JOIN SALGRADE S ON
-- 		E.SAL BETWEEN S.LOSAL AND S.HISAL LEFT JOIN
--         EMPS M ON E.MGR=M.EMPNO;   

-- SELECT
--     D.DEPTNO,
--     D.DNAME,
--     MIN(E.SAL) AS MIN_SAL,
--     MAX(E.SAL) AS MAX_SAL,
--     COUNT(*) AS NO_OF_MEMBERS
-- FROM EMPS E
-- JOIN DEPTS D
-- ON E.DEPTNO = D.DEPTNO
-- GROUP BY D.DEPTNO, D.DNAME
-- HAVING COUNT(*) >= 3;



-- CREATE TABLE CUSTOMER (
--     CUSTOMER_ID INT PRIMARY KEY,
--     CUSTOMER_NAME VARCHAR(100) NOT NULL,
--     CITY VARCHAR(50) NOT NULL
-- );

-- CREATE TABLE PRODUCTS (
--     PRODUCT_ID INT PRIMARY KEY,
--     PRODUCT_NAME VARCHAR(100) NOT NULL,
--     CATEGORY VARCHAR(50),
--     PRICE DECIMAL(10,2) NOT NULL
-- );


-- CREATE TABLE ORDERS (
--     ORDER_ID INT PRIMARY KEY,
--     CUSTOMER_ID INT,
--     PRODUCT_ID INT,
--     ORDER_DATE DATE,
--     QUANTITY INT,
--     TOTAL_AMOUNT DECIMAL(10,2),
--     
--     FOREIGN KEY (CUSTOMER_ID)
--     REFERENCES CUSTOMER(CUSTOMER_ID),
--     
--     FOREIGN KEY (PRODUCT_ID)
--     REFERENCES PRODUCTS(PRODUCT_ID)
-- );



-- INSERT INTO CUSTOMER VALUES
-- (101,'Rahul Sharma','Mumbai'),
-- (102,'Priya Verma','Bangalore'),
-- (103,'Amit Kumar','Delhi'),
-- (104,'Sneha Reddy','Hyderabad'),
-- (105,'Arjun Singh','Pune');

-- INSERT INTO PRODUCTS VALUES
-- (1,'Laptop','Electronics',65000),
-- (2,'Mobile','Electronics',25000),
-- (3,'Headphones','Accessories',3000),
-- (4,'Keyboard','Accessories',1500),
-- (5,'Monitor','Electronics',12000);

-- INSERT INTO ORDERS VALUES
-- (1001,101,1,'2025-01-10',1,65000),
-- (1002,102,2,'2025-01-15',1,25000),
-- (1003,101,3,'2025-02-01',2,6000),
-- (1004,103,4,'2025-02-05',1,1500),
-- (1005,104,5,'2025-02-10',1,12000),
-- (1006,105,2,'2025-02-15',2,50000);

-- SELECT
--     C.CUSTOMER_NAME,
--     SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
--     COUNT(*) AS TOTAL_NO_ORDERS
-- FROM CUSTOMER C
-- JOIN ORDERS O
-- ON C.CUSTOMER_ID = O.CUSTOMER_ID
-- GROUP BY C.CUSTOMER_NAME;

-- SELECT
--     C.CUSTOMER_NAME,
--     SUM(O.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
--     COUNT(*) AS TOTAL_NO_ORDERS
-- FROM CUSTOMER C
-- JOIN ORDERS O
-- ON C.CUSTOMER_ID = O.CUSTOMER_ID
-- GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
-- ORDER BY TOTAL_NO_ORDERS DESC
-- LIMIT 3;


-- SUBQUERY

-- SELECT E.ENAME,E.EMPNO,E.SAL FROM 
-- EMPS E WHERE E.SAL>=(SELECT SAL FROM EMPS E1 
-- WHERE E1.ENAME='ALLEN');

-- SELECT E.ENAME,E.EMPNO,E.SAL FROM 
-- EMPS E WHERE E.SAL>=(SELECT AVG(SAL) FROM EMPS E1 );

-- SELECT E.ENAME,E.EMPNO,E.SAL FROM 
-- EMPS E WHERE E.SAL>=(SELECT MAX(SAL) FROM EMPS E1 );

-- SELECT * FROM 
-- DEPTS D WHERE DEPTNO IN (SELECT DISTINCT DEPTNO FROM EMPS);

-- SELECT * FROM 
-- DEPTS D WHERE  EXISTS (SELECT 1  FROM EMPS E WHERE D.DEPTNO=E.DEPTNO);

-- SELECT * FROM 
-- DEPTS D WHERE  NOT EXISTS (SELECT 1  FROM EMPS E WHERE D.DEPTNO=E.DEPTNO);

-- SELECT * FROM 
-- EMPS E WHERE  EXISTS (SELECT 1  FROM DEPTS D WHERE D.DEPTNO=E.DEPTNO);

-- SELECT
--     E.EMPNO,
--     E.ENAME,
--     E.SAL
-- FROM EMPS E
-- WHERE E.SAL > (
--     SELECT AVG(SAL)
--     FROM EMPS
-- );


-- CORELATED SUBQUERY

-- SELECT * FROM EMPS E WHERE E.SAL>(SELECT AVG(E1.SAL) FROM EMPS E1
--  WHERE E.DEPTNO=E1.DEPTNO) ORDER BY DEPTNO;

-- CREATE TABLE FRUIT1 (
--     NAME VARCHAR(50)
-- );

-- CREATE TABLE FRUIT2 (
--     NAME VARCHAR(50)
-- );

-- INSERT INTO FRUIT1 VALUES
-- ('APPLE'),
-- ('MANGO'),
-- ('BANANA'),
-- ('ORANGE'),
-- ('GRAPES');

-- INSERT INTO FRUIT2 VALUES
-- ('APPLE'),
-- ('KIWI'),
-- ('BANANA'),
-- ('PAPAYA'),
-- ('GUAVA');

-- SELECT * FROM FRUIT1 UNION ALL SELECT * FROM  FRUIT2;

-- SELECT * FROM FRUIT1 UNION  SELECT * FROM  FRUIT2;

-- SELECT * FROM FRUIT1 F1
-- 	JOIN FRUIT2 F2 ON F1.NAME=F2.NAME;

-- SELECT NAME FROM FRUIT1
-- INTERSECT SELECT NAME FROM FRUIT2;

-- INNER JOIN     → Combines rows from both tables
-- INTERSECT      → Returns common values only





-- CREATE USER 'GURURAJ'@'localhost' IDENTIFIED BY 'root';
-- SELECT USER,HOST FROM MYSQL.USER;
-- SHOW GRANTS FOR 'GURURAJ'@'localhost';
-- GRANT SELECT, INSERT, UPDATE
-- ON training_db.*
-- TO 'GURURAJ'@'localhost';


-- REVOKE SELECT
-- ON training_db.*
-- FROM 'GURURAJ'@'localhost';

-- GRANT SELECT
-- ON training_db.*
-- TO 'GURURAJ'@'localhost';

-- SHOW GRANTS FOR 'GURURAJ'@'localhost';

-- GRANT SELECT ON training_db.emps to 'GURURAJ'@'localhost' with grant option;



-- TCL[TRANSCATION..]

-- INSERT INTO DEPTS VALUES(60,'IT','NEW YOORK'); --here autocommit is on  so cahnges visble in cmd

-- SET autocommit=0;
 -- INSERT INTO DEPTS VALUES(70,'IT','BOSTON'); -- not visble in another side(cmd)
 -- commit;
 
 
 -- UPDATE DEPTS SET LOC="INDIA" WHERE DEPTNO=60;
--  SELECT * FROM DEPTS;
--  ROLLBACK;
  -- SELECT * FROM DEPTS;
  
  
  
--   START TRANSACTION;
--   INSERT INTO DEPTS VALUES (80, 'HR',        'HYDERABAD');

-- INSERT INTO DEPTS VALUES (90, 'FINANCE',   'MUMBAI');

-- INSERT INTO DEPTS VALUES (100, 'MARKETING','BANGALORE');

-- INSERT INTO DEPTS VALUES (110, 'SUPPORT',  'PUNE');

-- INSERT INTO DEPTS VALUES (120, 'ADMIN',    'CHENNAI');

-- INSERT INTO DEPTS VALUES (130, 'LEGAL',    'DELHI');

-- INSERT INTO DEPTS VALUES (140, 'SECURITY', 'KOLKATA');

-- INSERT INTO DEPTS VALUES (150, 'DEVOPS',   'NOIDA');

-- INSERT INTO DEPTS VALUES (160, 'QA',       'MYSORE');

-- INSERT INTO DEPTS VALUES (170, 'R&D',      'AHMEDABAD');

-- SAVEPOINT AFTER_INSERT;
-- UPDATE DEPTS  SET LOC='INDIA' WHERE DEPTNO=20;

-- SELECT * FROM DEPTS;
--  
--  
-- ROLLBACK TO SAVEPOINT AFTER_INSERT;

-- SELECT * FROM DEPTS;
 -- COMMIT;