USE training_db;
-- CREATE TABLE DEPTS (
--     DEPTNO INT PRIMARY KEY,
--     DNAME VARCHAR(50),
--     LOC VARCHAR(50)
-- );

-- CREATE TABLE EMPS (
--     EMPNO INT PRIMARY KEY,
--     ENAME VARCHAR(50),
--     JOB VARCHAR(50),
--     MGR INT,
--     HIREDATE DATE,
--     SAL DECIMAL(10,2),
--     COMM DECIMAL(10,2),
--     DEPTNO INT,
--     FOREIGN KEY (DEPTNO) REFERENCES DEPTS(DEPTNO));

-- CREATE TABLE SALGRADE (
--     GRADE INT,
--     LOSAL INT,
--     HISAL INT
-- );

-- INSERT INTO DEPTS VALUES
-- (10, 'ACCOUNTING', 'NEW YORK'),
-- (20, 'RESEARCH', 'DALLAS'),
-- (30, 'SALES', 'CHICAGO'),
-- (40, 'OPERATIONS', 'BOSTON');


-- INSERT INTO EMPS VALUES
-- (7369, 'SMITH', 'CLERK', 7902, '1980-12-17', 800, NULL, 20),
-- (7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600, 300, 30),
-- (7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250, 500, 30),
-- (7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975, NULL, 20),
-- (7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850, NULL, 30),
-- (7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450, NULL, 10),
-- (7788, 'SCOTT', 'ANALYST', 7566, '1982-12-09', 3000, NULL, 20),
-- (7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000, NULL, 10),
-- (7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500, 0, 30),
-- (7876, 'ADAMS', 'CLERK', 7788, '1983-01-12', 1100, NULL, 20);

-- INSERT INTO SALGRADE VALUES
-- (1, 700, 1200),
-- (2, 1201, 1400),
-- (3, 1401, 2000),
-- (4, 2001, 3000),
-- (5, 3001, 9999);

-- SELECT * FROM SALGRADE;
-- SELECT * FROM DEPTS;
-- SELECT * FROM EMPS;

-- SELECT EMPNO,JOB,ENAME FROM EMPS;
-- SELECT DISTINCT JOB FROM EMPS;
-- SELECT DISTINCT JOB,DEPTNO FROM EMPS;
-- SELECT * FROM EMPS WHERE JOB='CLERK';

-- COMPARISION OPERATORS
-- SELECT EMPNO,JOB,ENAME FROM EMPS WHERE DEPTNO=10;		-- COLUMNS NOT IN SELECT CAN ALSO BE USED IN WHERE CLAUSE
-- SELECT EMPNO,JOB,ENAME FROM EMPS WHERE DEPTNO <> 10;		
-- SELECT EMPNO,JOB,ENAME FROM EMPS WHERE DEPTNO <> 10 AND DEPTNO <> 11;	
-- SELECT EMPNO,JOB,ENAME FROM EMPS WHERE DEPTNO NOT IN(10,11);	-- SAME AS ABOVE ONE
-- SELECT * FROM EMPS WHERE ENAME LIKE 'S%';
-- SELECT * FROM EMPS WHERE ENAME NOT LIKE 'S%';
-- SELECT * FROM EMPS WHERE ENAME  LIKE '__I%';

-- select* FROM EMPS WHERE COMM=NULL; --  NULL CANT BE COMAPRED WITH =(IS IS USED)
-- select * FROM EMPS WHERE COMM IS NULL;
-- select * FROM EMPS WHERE SAL BETWEEN 2000 AND 3000;

-- SELECT * FROM EMPS WHERE COMM=300 OR DEPTNO=30; 
-- SELECT * FROM EMPS WHERE COMM=300 AND DEPTNO=30; 

-- SELECT * FROM EMPS ORDER BY SAL ;	-- DEFAULT=ASC
-- SELECT * FROM EMPS ORDER BY SAL DESC;
-- SELECT * FROM EMPS ORDER BY SAL,DEPTNO ;
-- SELECT * FROM EMPS ORDER BY SAL,DEPTNO LIMIT 3 ;
-- SELECT * FROM EMPS ORDER BY SAL,DEPTNO DESC LIMIT 3 OFFSET 5;		-- SKIPS 5[OR LIMIT 5,3]


-- FUNCTIONS
-- STRING FUNCTIONS (CONCAT, UPPER, LOWER, LENGTH, SUBSTRING)
-- NUMERIC FUNCTIONS (ABS, ROUND, CEIL, FLOOR, MOD)
-- AGGREGATE FUNCTIONS (COUNT, SUM, AVG, MIN, MAX)
-- DATE FUNCTIONS (NOW, CURDATE, DATEDIFF, DATE_ADD)
-- NULL FUNCTIONS (IFNULL, COALESCE, NULLIF)
-- CONDITIONAL FUNCTIONS (IF, CASE)
-- CONVERSION FUNCTIONS (CAST, CONVERT)
-- WINDOW FUNCTIONS (ROW_NUMBER, RANK, DENSE_RANK)
-- SYSTEM FUNCTIONS (USER, DATABASE, VERSION)


-- SELECT length('GURURAJ') NUMBER_OF_CHARACTERS;
-- SELECT * FROM EMPS WHERE LENGTH(ENAME)>=5;
-- SELECT * FROM EMPS ORDER BY LENGTH(ENAME);

-- SELECT CHAR(66);

-- SELECT CONCAT(ENAME,'S  SALARY IS :',SAL) AS DETAILS FROM EMPS;
-- SELECT CONCAT(
--     EMPNO, ' ',ENAME, ' ',JOB, ' ',MGR, ' ',HIREDATE, ' ',SAL, ' ',COMM, ' ',DEPTNO) AS EMP_DETAILS
-- FROM EMPS;


-- SELECT CONCAT_WS(
--     ' ',
--     EMPNO,
--     ENAME,
--     JOB,
--     MGR,
--     HIREDATE,
--     SAL,
--     COMM,
--     DEPTNO
-- ) AS EMP_DETAILS
-- FROM EMPS;


-- SELECT EMPNO,ENAME,RIGHT(ENAME,2) AS LAST_TWO FROM EMPS;
-- SELECT EMPNO,ENAME,SUBSTRING(ENAME,3,3) AS MIDDLE FROM EMPS;
-- SELECT EMPNO,ENAME,SUBSTRING(ENAME,3) AS THIRD_TO_LAST FROM EMPS;
-- SELECT EMPNO,ENAME,INSTR(ENAME,'T') AS OCCURENCE_POS FROM EMPS;
-- SELECT INSTR('GURURAJ SHETTY',' ') AS OCCURENCE_POS ;

-- CREATE TABLE DUMMY(NAME VARCHAR(30));
-- INSERT INTO DUMMY VALUES ('Ram Kumar'), 
-- ('Shyam Sharma'), ('Sita Devi'), ('Geeta Patel'), ('Rahul Verma');

-- SELECT NAME,
--     SUBSTRI-- NG_INDEX(NAME, ' ', 1) AS FIRST_NAME,
-- --     SUBSTRING_INDEX(NAME, ' ', -1) AS LAST_NAME
-- -- FROM DUMMY;


-- -- SELECT ENAME,LPAD(ENAME,30,'*') ENAME_LPAD FROM EMPS;
-- -- SELECT ENAME,RPAD(ENAME,30,'*') ENAME_RPAD FROM EMPS;

-- -- SELECT * FROM EMPS WHERE TRIM(ENAME)='SMITH';
-- -- SELECT * FROM EMPS WHERE LTRIM(ENAME)='SMITH';
-- -- SELECT * FROM EMPS WHERE RTRIM(ENAME)='SMITH';

-- -- SELECT * FROM EMPS WHERE UPPER(ENAME)='SMITH';
-- -- SELECT * FROM EMPS WHERE LOWER(ENAME)='SMITH';

-- SELECT CONCAT(UPPER(LEFT(TRIM(ENAME),1)),LOWER(SUBSTR(TRIM(ENAME),2)))  AS CAMELCASE FROM EMPS;

-- select REPEAT(ENAME,4)EMP_4_TIMES FROM EMPS;
-- select ENAME , REVERSE(ENAME)EMP_REV FROM EMPS;
-- SELECT 'I LOVE PYTHON ' AS ORIGINAL ,REPLACE('I LOVE PYTHON','PYTHON','JAVA') REPLACED;
-- SELECT STRCMP('GURURAJ','SHETTY');
-- SELECT STRCMP('GURURAJ','GURURAJ');


-- SELECT ABS(-1);
-- SELECT POW(10,2);
-- SELECT SQRT(9);
-- SELECT SQRT(65);
-- SELECT PI();
-- SELECT CEIL(10.5);
-- SELECT FLOOR(10.5);
-- SELECT LOG(10);
-- SELECT LOG2(10);
-- SELECT LOG10(10);
-- SELECT EXP(10);
-- SELECT SIN(1);
-- SELECT COS(1);
-- SELECT TAN(1);
-- SELECT ROUND(10.78);



